version: '3.8'
services:
  apache:
    image: httpd:alpine
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./docker/apache/usr/local/apache2/conf/httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: ./app
        target: /var/www/html
  php:
    build:
      dockerfile: ./docker/php/dockerfile
    environment:
      - MYSQL_USER=jojo
      - MYSQL_PASSWORD=jojo123
      - MYSQL_DATABASE=phpdb2
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
  mysql:
    image: mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Jonathan30.
      - MYSQL_USER=jojo
      - MYSQL_PASSWORD=jojo123
      - MYSQL_DATABASE=phpdb2
    volumes:
      - type: volume
        source: database
        target: /var/lib/mysql
volumes:
  database: